plugins {
    id 'com.android.application'
}

android {
    namespace 'com.revex.app'
    compileSdk 35

    defaultConfig {
        applicationId 'com.revex.app'
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName '1.0'
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.0'
}

configurations.all {
    resolutionStrategy.eachDependency { details ->
        if (details.requested.group == 'org.jetbrains.kotlin' &&
                details.requested.name.startsWith('kotlin-stdlib')) {
            details.useVersion '1.8.22'
        }
    }
}